# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Export
else:
    import _Export

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Export.delete_SwigPyIterator

    def value(self):
        return _Export.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Export.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Export.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Export.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Export.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Export.SwigPyIterator_copy(self)

    def next(self):
        return _Export.SwigPyIterator_next(self)

    def __next__(self):
        return _Export.SwigPyIterator___next__(self)

    def previous(self):
        return _Export.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Export.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Export.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Export.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Export.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Export.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Export.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Export.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _Export:
_Export.SwigPyIterator_swigregister(SwigPyIterator)

class CExporter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Export.CExporter_swiginit(self, _Export.new_CExporter())
    __swig_destroy__ = _Export.delete_CExporter

    def OutputDomainToIGES(self, szFileName, Domain):
        return _Export.CExporter_OutputDomainToIGES(self, szFileName, Domain)

    def OutputDomainToSTEP(self, szFileName, Domain):
        return _Export.CExporter_OutputDomainToSTEP(self, szFileName, Domain)

    def OutputTextileToIGES(self, *args):
        return _Export.CExporter_OutputTextileToIGES(self, *args)

    def OutputTextileToSTEP(self, *args):
        return _Export.CExporter_OutputTextileToSTEP(self, *args)

    def GetFaceted(self):
        return _Export.CExporter_GetFaceted(self)

    def GetExportDomain(self):
        return _Export.CExporter_GetExportDomain(self)

    def GetSubtractYarns(self):
        return _Export.CExporter_GetSubtractYarns(self)

    def SetFaceted(self, bFaceted):
        return _Export.CExporter_SetFaceted(self, bFaceted)

    def SetExportDomain(self, bExportDomain):
        return _Export.CExporter_SetExportDomain(self, bExportDomain)

    def SetSubtractYarns(self, bSubtractYarns):
        return _Export.CExporter_SetSubtractYarns(self, bSubtractYarns)

    def SetJoinYarns(self, bJoinYarns):
        return _Export.CExporter_SetJoinYarns(self, bJoinYarns)

# Register CExporter in _Export:
_Export.CExporter_swigregister(CExporter)



