# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Renderer
else:
    import _Renderer

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Renderer.delete_SwigPyIterator

    def value(self):
        return _Renderer.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Renderer.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Renderer.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Renderer.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Renderer.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Renderer.SwigPyIterator_copy(self)

    def next(self):
        return _Renderer.SwigPyIterator_next(self)

    def __next__(self):
        return _Renderer.SwigPyIterator___next__(self)

    def previous(self):
        return _Renderer.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Renderer.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Renderer.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Renderer.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Renderer.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Renderer.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Renderer.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Renderer.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _Renderer:
_Renderer.SwigPyIterator_swigregister(SwigPyIterator)

class LessPairDoubleInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, x, y):
        return _Renderer.LessPairDoubleInt___call__(self, x, y)

    def __init__(self):
        _Renderer.LessPairDoubleInt_swiginit(self, _Renderer.new_LessPairDoubleInt())
    __swig_destroy__ = _Renderer.delete_LessPairDoubleInt

# Register LessPairDoubleInt in _Renderer:
_Renderer.LessPairDoubleInt_swigregister(LessPairDoubleInt)

class LessPairDoubleXYZ(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, x, y):
        return _Renderer.LessPairDoubleXYZ___call__(self, x, y)

    def __init__(self):
        _Renderer.LessPairDoubleXYZ_swiginit(self, _Renderer.new_LessPairDoubleXYZ())
    __swig_destroy__ = _Renderer.delete_LessPairDoubleXYZ

# Register LessPairDoubleXYZ in _Renderer:
_Renderer.LessPairDoubleXYZ_swigregister(LessPairDoubleXYZ)

class COLOR(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r = property(_Renderer.COLOR_r_get, _Renderer.COLOR_r_set)
    g = property(_Renderer.COLOR_g_get, _Renderer.COLOR_g_set)
    b = property(_Renderer.COLOR_b_get, _Renderer.COLOR_b_set)

    def __init__(self, *args):
        _Renderer.COLOR_swiginit(self, _Renderer.new_COLOR(*args))

    def Array(self):
        return _Renderer.COLOR_Array(self)
    __swig_destroy__ = _Renderer.delete_COLOR

# Register COLOR in _Renderer:
_Renderer.COLOR_swigregister(COLOR)

OUTPUT_MINIMAL = _Renderer.OUTPUT_MINIMAL
OUTPUT_STANDARD = _Renderer.OUTPUT_STANDARD
OUTPUT_FULL = _Renderer.OUTPUT_FULL
INP_EXPORT = _Renderer.INP_EXPORT
VTU_EXPORT = _Renderer.VTU_EXPORT
SCIRUN_EXPORT = _Renderer.SCIRUN_EXPORT
BOX_DOMAIN = _Renderer.BOX_DOMAIN
SHEARED_DOMAIN = _Renderer.SHEARED_DOMAIN
ROTATED_DOMAIN = _Renderer.ROTATED_DOMAIN
PRISM_DOMAIN = _Renderer.PRISM_DOMAIN

def GetIndexedColor(iIndex):
    return _Renderer.GetIndexedColor(iIndex)

def CopyToRange(Offsets, Vector, iLowerLimit, iUpperLimit):
    return _Renderer.CopyToRange(Offsets, Vector, iLowerLimit, iUpperLimit)

def ConvertUnits(dValue, SourceUnits, TargetUnits):
    return _Renderer.ConvertUnits(dValue, SourceUnits, TargetUnits)

def CompatibleUnits(SourceUnits, TargetUnits, pErrorMessage=None):
    return _Renderer.CompatibleUnits(SourceUnits, TargetUnits, pErrorMessage)

def ReduceUnits(Units):
    return _Renderer.ReduceUnits(Units)

def AddNewUnits(NewUnit, BaseUnits):
    return _Renderer.AddNewUnits(NewUnit, BaseUnits)

def StripPath(Filename):
    return _Renderer.StripPath(Filename)

def AddExtensionIfMissing(Filename, Extension):
    return _Renderer.AddExtensionIfMissing(Filename, Extension)

def ReplaceFilenameSpaces(Filename):
    return _Renderer.ReplaceFilenameSpaces(Filename)

def RemoveExtension(Filename, Extension):
    return _Renderer.RemoveExtension(Filename, Extension)

def WriteOrientationsHeader(Output):
    return _Renderer.WriteOrientationsHeader(Output)

def WriteElementsHeader(Output):
    return _Renderer.WriteElementsHeader(Output)
class POINT_INFO(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iYarnIndex = property(_Renderer.POINT_INFO_iYarnIndex_get, _Renderer.POINT_INFO_iYarnIndex_set)
    YarnTangent = property(_Renderer.POINT_INFO_YarnTangent_get, _Renderer.POINT_INFO_YarnTangent_set)
    Location = property(_Renderer.POINT_INFO_Location_get, _Renderer.POINT_INFO_Location_set)
    dVolumeFraction = property(_Renderer.POINT_INFO_dVolumeFraction_get, _Renderer.POINT_INFO_dVolumeFraction_set)
    dSurfaceDistance = property(_Renderer.POINT_INFO_dSurfaceDistance_get, _Renderer.POINT_INFO_dSurfaceDistance_set)
    Orientation = property(_Renderer.POINT_INFO_Orientation_get, _Renderer.POINT_INFO_Orientation_set)
    Up = property(_Renderer.POINT_INFO_Up_get, _Renderer.POINT_INFO_Up_set)

    def __init__(self):
        _Renderer.POINT_INFO_swiginit(self, _Renderer.new_POINT_INFO())
    __swig_destroy__ = _Renderer.delete_POINT_INFO

# Register POINT_INFO in _Renderer:
_Renderer.POINT_INFO_swigregister(POINT_INFO)

class MESHER_ELEMENT_DATA(POINT_INFO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iLayer = property(_Renderer.MESHER_ELEMENT_DATA_iLayer_get, _Renderer.MESHER_ELEMENT_DATA_iLayer_set)
    iRegion = property(_Renderer.MESHER_ELEMENT_DATA_iRegion_get, _Renderer.MESHER_ELEMENT_DATA_iRegion_set)

    def __init__(self):
        _Renderer.MESHER_ELEMENT_DATA_swiginit(self, _Renderer.new_MESHER_ELEMENT_DATA())
    __swig_destroy__ = _Renderer.delete_MESHER_ELEMENT_DATA

# Register MESHER_ELEMENT_DATA in _Renderer:
_Renderer.MESHER_ELEMENT_DATA_swigregister(MESHER_ELEMENT_DATA)


def GetMinMaxXY(Points, Min, Max):
    return _Renderer.GetMinMaxXY(Points, Min, Max)
MATERIAL_CONTINUUM = _Renderer.MATERIAL_CONTINUUM
SINGLE_LAYER_RVE = _Renderer.SINGLE_LAYER_RVE
STAGGERED_BC = _Renderer.STAGGERED_BC
SHEARED_BC = _Renderer.SHEARED_BC
ROTATED_BC = _Renderer.ROTATED_BC
NO_BOUNDARY_CONDITIONS = _Renderer.NO_BOUNDARY_CONDITIONS
BENDING_BC = _Renderer.BENDING_BC
class PROP_INFO(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _Renderer.delete_PROP_INFO

    def __init__(self):
        _Renderer.PROP_INFO_swiginit(self, _Renderer.new_PROP_INFO())

# Register PROP_INFO in _Renderer:
_Renderer.PROP_INFO_swigregister(PROP_INFO)

class PROP_YARN_INFO(PROP_INFO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    TextileName = property(_Renderer.PROP_YARN_INFO_TextileName_get, _Renderer.PROP_YARN_INFO_TextileName_set)
    iYarn = property(_Renderer.PROP_YARN_INFO_iYarn_get, _Renderer.PROP_YARN_INFO_iYarn_set)

    def __init__(self):
        _Renderer.PROP_YARN_INFO_swiginit(self, _Renderer.new_PROP_YARN_INFO())
    __swig_destroy__ = _Renderer.delete_PROP_YARN_INFO

# Register PROP_YARN_INFO in _Renderer:
_Renderer.PROP_YARN_INFO_swigregister(PROP_YARN_INFO)

class PROP_NODE_INFO(PROP_INFO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    TextileName = property(_Renderer.PROP_NODE_INFO_TextileName_get, _Renderer.PROP_NODE_INFO_TextileName_set)
    iYarn = property(_Renderer.PROP_NODE_INFO_iYarn_get, _Renderer.PROP_NODE_INFO_iYarn_set)
    iNode = property(_Renderer.PROP_NODE_INFO_iNode_get, _Renderer.PROP_NODE_INFO_iNode_set)

    def __init__(self):
        _Renderer.PROP_NODE_INFO_swiginit(self, _Renderer.new_PROP_NODE_INFO())
    __swig_destroy__ = _Renderer.delete_PROP_NODE_INFO

# Register PROP_NODE_INFO in _Renderer:
_Renderer.PROP_NODE_INFO_swigregister(PROP_NODE_INFO)

class PROP_IMAGE_INFO(PROP_INFO):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iImageID = property(_Renderer.PROP_IMAGE_INFO_iImageID_get, _Renderer.PROP_IMAGE_INFO_iImageID_set)

    def __init__(self):
        _Renderer.PROP_IMAGE_INFO_swiginit(self, _Renderer.new_PROP_IMAGE_INFO())
    __swig_destroy__ = _Renderer.delete_PROP_IMAGE_INFO

# Register PROP_IMAGE_INFO in _Renderer:
_Renderer.PROP_IMAGE_INFO_swigregister(PROP_IMAGE_INFO)


def __lt__(*args):
    return _Renderer.__lt__(*args)
class CTexGenRenderer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, pRenderWindowInteractor=None):
        _Renderer.CTexGenRenderer_swiginit(self, _Renderer.new_CTexGenRenderer(pRenderWindowInteractor))
    __swig_destroy__ = _Renderer.delete_CTexGenRenderer
    PROP_NODE = _Renderer.CTexGenRenderer_PROP_NODE
    PROP_PATH = _Renderer.CTexGenRenderer_PROP_PATH
    PROP_SURFACE = _Renderer.CTexGenRenderer_PROP_SURFACE
    PROP_VOLUME = _Renderer.CTexGenRenderer_PROP_VOLUME
    PROP_AXES = _Renderer.CTexGenRenderer_PROP_AXES
    PROP_INTERFERENCE = _Renderer.CTexGenRenderer_PROP_INTERFERENCE
    PROP_ORIENTATION = _Renderer.CTexGenRenderer_PROP_ORIENTATION
    PROP_DOMAIN = _Renderer.CTexGenRenderer_PROP_DOMAIN
    PROP_DOMAINAXES = _Renderer.CTexGenRenderer_PROP_DOMAINAXES
    PROP_IMAGE = _Renderer.CTexGenRenderer_PROP_IMAGE
    PROP_INTERFERENCE_DEPTH = _Renderer.CTexGenRenderer_PROP_INTERFERENCE_DEPTH
    EXPORT_NODES = _Renderer.CTexGenRenderer_EXPORT_NODES
    EXPORT_PATH = _Renderer.CTexGenRenderer_EXPORT_PATH
    EXPORT_SURFACE = _Renderer.CTexGenRenderer_EXPORT_SURFACE
    EXPORT_DOMAIN = _Renderer.CTexGenRenderer_EXPORT_DOMAIN

    def RenderTextile(self, *args):
        return _Renderer.CTexGenRenderer_RenderTextile(self, *args)

    def RenderYarn(self, *args):
        return _Renderer.CTexGenRenderer_RenderYarn(self, *args)

    def RenderMesh(self, *args):
        return _Renderer.CTexGenRenderer_RenderMesh(self, *args)

    def RenderYarnMesh(self, *args):
        return _Renderer.CTexGenRenderer_RenderYarnMesh(self, *args)

    def RenderDomain(self, *args):
        return _Renderer.CTexGenRenderer_RenderDomain(self, *args)

    def RenderDomainAxes(self, *args):
        return _Renderer.CTexGenRenderer_RenderDomainAxes(self, *args)

    def RenderNodes(self, *args):
        return _Renderer.CTexGenRenderer_RenderNodes(self, *args)

    def RenderPaths(self, *args):
        return _Renderer.CTexGenRenderer_RenderPaths(self, *args)

    def RenderPath(self, Textile, iYarn):
        return _Renderer.CTexGenRenderer_RenderPath(self, Textile, iYarn)

    def RenderInterference(self, *args):
        return _Renderer.CTexGenRenderer_RenderInterference(self, *args)

    def RenderGrid(self, *args):
        return _Renderer.CTexGenRenderer_RenderGrid(self, *args)

    def SetBackgroundColor(self, Color):
        return _Renderer.CTexGenRenderer_SetBackgroundColor(self, Color)

    def RenderAxes(self):
        return _Renderer.CTexGenRenderer_RenderAxes(self)

    def ClearScene(self):
        return _Renderer.CTexGenRenderer_ClearScene(self)

    def RemoveProps(self, Type):
        return _Renderer.CTexGenRenderer_RemoveProps(self, Type)

    def SetPropsColor(self, Type, Color):
        return _Renderer.CTexGenRenderer_SetPropsColor(self, Type, Color)

    def GetNumProps(self, Type):
        return _Renderer.CTexGenRenderer_GetNumProps(self, Type)

    def GetYarnPropInfo(self, pProp):
        return _Renderer.CTexGenRenderer_GetYarnPropInfo(self, pProp)

    def GetNodePropInfo(self, pProp):
        return _Renderer.CTexGenRenderer_GetNodePropInfo(self, pProp)

    def GetImagePropInfo(self, pProp):
        return _Renderer.CTexGenRenderer_GetImagePropInfo(self, pProp)

    def GetProps(self, *args):
        return _Renderer.CTexGenRenderer_GetProps(self, *args)

    def GetNodeProps(self, Info, bIgnoreTextileName=False):
        return _Renderer.CTexGenRenderer_GetNodeProps(self, Info, bIgnoreTextileName)

    def RefreshYarn(self, YarnInfo):
        return _Renderer.CTexGenRenderer_RefreshYarn(self, YarnInfo)

    def RefreshTextile(self, TextileName):
        return _Renderer.CTexGenRenderer_RefreshTextile(self, TextileName)

    def ResetCamera(self, *args):
        return _Renderer.CTexGenRenderer_ResetCamera(self, *args)

    def RefreshView(self):
        return _Renderer.CTexGenRenderer_RefreshView(self)

    def Start(self, bTakeControl=True, iWidth=800, iHeight=600, bFullScreen=False):
        return _Renderer.CTexGenRenderer_Start(self, bTakeControl, iWidth, iHeight, bFullScreen)

    def TakeScreenShot(self, FileName, iMagnification=1):
        return _Renderer.CTexGenRenderer_TakeScreenShot(self, FileName, iMagnification)

    def SetParallelProjection(self, bParallelProjection):
        return _Renderer.CTexGenRenderer_SetParallelProjection(self, bParallelProjection)

    def GetRenderer(self):
        return _Renderer.CTexGenRenderer_GetRenderer(self)

    def GetInteractor(self):
        return _Renderer.CTexGenRenderer_GetInteractor(self)

    def SetCallback(self, pCallback):
        return _Renderer.CTexGenRenderer_SetCallback(self, pCallback)

    def SetXRay(self, bXRay):
        return _Renderer.CTexGenRenderer_SetXRay(self, bXRay)

    def SetTrimToDomain(self, bTrim):
        return _Renderer.CTexGenRenderer_SetTrimToDomain(self, bTrim)

    def SetYarnColor(self, iYarn, Color):
        return _Renderer.CTexGenRenderer_SetYarnColor(self, iYarn, Color)

    @staticmethod
    def ApplyColor(pActor, Color):
        return _Renderer.CTexGenRenderer_ApplyColor(pActor, Color)

    def ApplyDefaultColor(self, pActor):
        return _Renderer.CTexGenRenderer_ApplyDefaultColor(self, pActor)

    def SaveTextileToVTK(self, *args):
        return _Renderer.CTexGenRenderer_SaveTextileToVTK(self, *args)

    def SaveMeshToVTK(self, FileName, Mesh):
        return _Renderer.CTexGenRenderer_SaveMeshToVTK(self, FileName, Mesh)

    def BeginBatch(self):
        return _Renderer.CTexGenRenderer_BeginBatch(self)

    def EndBatch(self):
        return _Renderer.CTexGenRenderer_EndBatch(self)

    def RemoveNodes(self):
        return _Renderer.CTexGenRenderer_RemoveNodes(self)

    def RemovePaths(self):
        return _Renderer.CTexGenRenderer_RemovePaths(self)

    def RemoveTextiles(self):
        return _Renderer.CTexGenRenderer_RemoveTextiles(self)

    def RemoveMeshes(self):
        return _Renderer.CTexGenRenderer_RemoveMeshes(self)

    def RemoveAxes(self):
        return _Renderer.CTexGenRenderer_RemoveAxes(self)

    def RemoveInterference(self):
        return _Renderer.CTexGenRenderer_RemoveInterference(self)

    def RemoveInterferenceDepth(self):
        return _Renderer.CTexGenRenderer_RemoveInterferenceDepth(self)

    def RemoveOrientations(self):
        return _Renderer.CTexGenRenderer_RemoveOrientations(self)

    def RemoveDomains(self):
        return _Renderer.CTexGenRenderer_RemoveDomains(self)

    def RemoveDomainAxes(self):
        return _Renderer.CTexGenRenderer_RemoveDomainAxes(self)

    def GetPolyData(self, Mesh):
        return _Renderer.CTexGenRenderer_GetPolyData(self, Mesh)

    def GetXRay(self):
        return _Renderer.CTexGenRenderer_GetXRay(self)

    def GetTrimToDomain(self):
        return _Renderer.CTexGenRenderer_GetTrimToDomain(self)

    def GetParallelProjection(self):
        return _Renderer.CTexGenRenderer_GetParallelProjection(self)

# Register CTexGenRenderer in _Renderer:
_Renderer.CTexGenRenderer_swigregister(CTexGenRenderer)

def CTexGenRenderer_ApplyColor(pActor, Color):
    return _Renderer.CTexGenRenderer_ApplyColor(pActor, Color)



